
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'
import { ThemeProvider } from 'next-themes'
import { ToastContainer } from 'react-toastify'


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <ClerkProvider>
      
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
               <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                
      <Navbar/>
      <ToastContainer/>
          {children}
               </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}